package com.wujunshen.entity;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_book.bookId
     *
     * @mbggenerated Mon Nov 21 14:11:40 CST 2016
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_book.bookName
     *
     * @mbggenerated Mon Nov 21 14:11:40 CST 2016
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_book.publisher
     *
     * @mbggenerated Mon Nov 21 14:11:40 CST 2016
     */
    private String publisher;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simple_book.bookId
     *
     * @return the value of simple_book.bookId
     *
     * @mbggenerated Mon Nov 21 14:11:40 CST 2016
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simple_book.bookId
     *
     * @param bookId the value for simple_book.bookId
     *
     * @mbggenerated Mon Nov 21 14:11:40 CST 2016
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simple_book.bookName
     *
     * @return the value of simple_book.bookName
     *
     * @mbggenerated Mon Nov 21 14:11:40 CST 2016
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simple_book.bookName
     *
     * @param bookName the value for simple_book.bookName
     *
     * @mbggenerated Mon Nov 21 14:11:40 CST 2016
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column simple_book.publisher
     *
     * @return the value of simple_book.publisher
     *
     * @mbggenerated Mon Nov 21 14:11:40 CST 2016
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column simple_book.publisher
     *
     * @param publisher the value for simple_book.publisher
     *
     * @mbggenerated Mon Nov 21 14:11:40 CST 2016
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_book
     *
     * @mbggenerated Mon Nov 21 14:11:40 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Book other = (Book) that;
        return (this.getBookId() == null ? other.getBookId() == null : this.getBookId().equals(other.getBookId()))
            && (this.getBookName() == null ? other.getBookName() == null : this.getBookName().equals(other.getBookName()))
            && (this.getPublisher() == null ? other.getPublisher() == null : this.getPublisher().equals(other.getPublisher()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_book
     *
     * @mbggenerated Mon Nov 21 14:11:40 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBookId() == null) ? 0 : getBookId().hashCode());
        result = prime * result + ((getBookName() == null) ? 0 : getBookName().hashCode());
        result = prime * result + ((getPublisher() == null) ? 0 : getPublisher().hashCode());
        return result;
    }
}