package com.youmeek.ssm.pojo;

public class Childcol {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column childcol.id
     *
     * @mbggenerated
     */
    private Integer chId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column childcol.childcol_en
     *
     * @mbggenerated
     */
    private String childcolEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column childcol.childcol_cn
     *
     * @mbggenerated
     */
    private String childcolCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column childcol.spcolumn_id
     *
     * @mbggenerated
     */
    private Integer spcolumnId;

    public Integer getChId() {
        return chId;
    }

    public void setChId(Integer chId) {
        this.chId = chId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column childcol.childcol_en
     *
     * @return the value of childcol.childcol_en
     *
     * @mbggenerated
     */
    public String getChildcolEn() {
        return childcolEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column childcol.childcol_en
     *
     * @param childcolEn the value for childcol.childcol_en
     *
     * @mbggenerated
     */
    public void setChildcolEn(String childcolEn) {
        this.childcolEn = childcolEn == null ? null : childcolEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column childcol.childcol_cn
     *
     * @return the value of childcol.childcol_cn
     *
     * @mbggenerated
     */
    public String getChildcolCn() {
        return childcolCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column childcol.childcol_cn
     *
     * @param childcolCn the value for childcol.childcol_cn
     *
     * @mbggenerated
     */
    public void setChildcolCn(String childcolCn) {
        this.childcolCn = childcolCn == null ? null : childcolCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column childcol.spcolumn_id
     *
     * @return the value of childcol.spcolumn_id
     *
     * @mbggenerated
     */
    public Integer getSpcolumnId() {
        return spcolumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column childcol.spcolumn_id
     *
     * @param spcolumnId the value for childcol.spcolumn_id
     *
     * @mbggenerated
     */
    public void setSpcolumnId(Integer spcolumnId) {
        this.spcolumnId = spcolumnId;
    }
}