package com.youmeek.ssm.mapper;


import com.youmeek.ssm.pojo.Childcol;

public interface ChildcolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table childcol
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table childcol
     *
     * @mbggenerated
     */
    int insert(Childcol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table childcol
     *
     * @mbggenerated
     */
    int insertSelective(Childcol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table childcol
     *
     * @mbggenerated
     */
    Childcol selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table childcol
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Childcol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table childcol
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Childcol record);
}