package com.youmeek.ssm.mapper;

import com.github.pagehelper.Page;
import com.github.pagehelper.PageInfo;
import com.youmeek.ssm.pojo.EventDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EventDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated
     */
    int insert(EventDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated
     */
    int insertSelective(EventDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated
     */
    EventDetail selectByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EventDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EventDetail record);

    /**
     * 根据消防员id和事件id获取所有事件详情
     * @Author frank.fang
     * @Date 2016/4/25 17:17
     */
    List<EventDetail> getEventDetailByManAndEventId(@Param("firemanId") Integer firemanId, @Param("eventId") Integer eventId);

    /**
     * 根据事件id获取所有事件详情
     * @Author frank.fang
     * @Date 2016/4/25 17:35
     */
    List<EventDetail> getEventDetailByEventId(@Param("eventId") Integer eventId);

    /**
     *
     * @Author frank.fang
     * @Date 2016/4/28 17:07
     */
    Page<EventDetail> listEventDetail();

    /**
     *
     * @Author frank.fang
     * @Date 2016/5/3 9:54
     */
    void delByIdList(@Param("idList") List<String> idList);

}