package com.youmeek.ssm.mapper;

import com.youmeek.ssm.pojo.Spcolumn;

import java.util.List;

public interface SpcolumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spcolumn
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spcolumn
     *
     * @mbggenerated
     */
    int insert(Spcolumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spcolumn
     *
     * @mbggenerated
     */
    int insertSelective(Spcolumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spcolumn
     *
     * @mbggenerated
     */
    Spcolumn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spcolumn
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Spcolumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spcolumn
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Spcolumn record);

    /**
     * 获取所有一级标题
     * @Author frank.fang
     * @Date 2016/5/5 9:41
     */
    List<Spcolumn> getAllSpCol();
}