package com.youmeek.ssm.mapper;


import com.youmeek.ssm.pojo.Fireman;

import java.util.List;

public interface FiremanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fireman
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer firemanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fireman
     *
     * @mbggenerated
     */
    int insert(Fireman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fireman
     *
     * @mbggenerated
     */
    int insertSelective(Fireman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fireman
     *
     * @mbggenerated
     */
    Fireman selectByPrimaryKey(Integer firemanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fireman
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fireman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fireman
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fireman record);

    /**
     * 获取所有消防员
     * @Author frank.fang
     * @Date 2016/4/29 17:09
     */
    List<Fireman> getAllFireman();
}