package com.youmeek.ssm.mapper;

import com.youmeek.ssm.pojo.ReceiveEvent;

public interface ReceiveEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_event
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_event
     *
     * @mbggenerated
     */
    int insert(ReceiveEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_event
     *
     * @mbggenerated
     */
    int insertSelective(ReceiveEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_event
     *
     * @mbggenerated
     */
    ReceiveEvent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReceiveEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReceiveEvent record);
}